# Generated by Django 5.0.6 on 2024-05-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectileMotionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.FloatField()),
                ("velocity", models.FloatField()),
                ("angle", models.FloatField()),
                ("mass", models.FloatField()),
                ("c_F", models.FloatField()),
                ("xmax", models.FloatField()),
                ("ymax", models.FloatField()),
            ],
        ),
    ]
